app:
  name: CurrencyExchangeApp
  port: :3000

database:
   dsn: root:123456@tcp(127.0.0.1:3306)/myassistapp?charset=utf8mb4&parseTime=True&loc=Local
   MaxIdleConns: 10
   MaxOpenConns: 100

redis:
   addr: 192.168.246.131:6379
   password: "123456"
   dc: 0